# Generated by Django 5.0.6 on 2026-04-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_create_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('storekeeper', 'Store Keeper'), ('manager', 'Manager / Admin')], default='storekeeper', max_length=20),
        ),
    ]
