# Generated by Django 5.0.6 on 2026-04-22 20:05

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebatch',
            name='is_voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issuebatch',
            name='void_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='issuebatch',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuebatch',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_issue_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='distributionline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='item',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(choices=[('damage', 'Damage / wastage'), ('count', 'Stock count correction'), ('return', 'Customer / department return'), ('expired', 'Expired / unusable'), ('other', 'Other')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('adjusted_at', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory.item')),
            ],
            options={
                'ordering': ['-adjusted_at', '-id'],
            },
        ),
    ]
