# Generated by Django 5.0.6 on 2026-04-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_issuebatch_is_voided_issuebatch_void_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("viewer", "Viewer"),
                    ("storekeeper", "Store Keeper"),
                    ("manager", "Manager"),
                    ("admin", "Admin"),
                ],
                default="storekeeper",
                max_length=20,
            ),
        ),
    ]
